In [17]:
import numpy as np
class Board:
    def __init__(self):
        self.board = np.zeros((3,3))
        
    def wining(self):
        """
        returns 1 if p1 wins
        -1 if p2 wins
        0 if all done 
        None if nothing has happneded 
        """
        if(np.any(np.sum(self.board,axis=0)==3)):
            return 1
        if( np.any(np.sum(self.board,axis=0) == -3)):
            return -1
        if(np.any(np.sum(self.board,axis=1)==3)):
            return 1
        if(np.any(np.sum(self.board,axis=1)==-3)):
            return -1
        # diagonals 
        if (np.trace(self.board))==3 or (np.trace(np.fliplr(self.board)))==3:
            return 1
        if (np.trace(self.board))==-3 or (np.trace(np.fliplr(self.board)))==-3:
            return -1
        if(self._alldone()):
            return 0
        return None
    def _alldone(self):
        np.any(self.board==0)
        
    def availble_positions(self):
        ans = []
        for i in range(3):
            for j in range(3):
                if(self.board[i][j]==0):
                    ans.append((i,j))
        return ans
    def print_board(self):
        for i in self.board:
            print(i)
            

In [ ]:
class Game(Board):
    def__init__(self,p1=1,p2=-1):
        super().__init__()
        self.p1 = p1
        self.p2 =p2
    
    def play(self):
        """
        the main runner of the game its where we give the input and the 
        adversial search gives back its input
        we check if the game is won/tied 
        if not repeat the process
        """
        
        while True:
            self.print_positions()
            print("you can take any position which is 0")
            row = int(input("enter your row: "))
            col = int(input("enter your col: "))
            
            if(self.board[i][j]==0):
                self.board[i][j]= 1
            else :
                print("invalid move")

In [18]:
game = Board()
print(game.availble_positions())
game.print_board()

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
