In [11]:
import numpy as np
class Board:
    def __init__(self):
        self.board = np.zeros((3,3))
        
    def winning(self):
        """
        returns 1 if p1 wins
        -1 if p2 wins
        0 if all done 
        None if nothing has happneded 
        """
        if(np.any(np.sum(self.board,axis=0)==3)):
            return 1
        if( np.any(np.sum(self.board,axis=0) == -3)):
            return -1
        if(np.any(np.sum(self.board,axis=1)==3)):
            return 1
        if(np.any(np.sum(self.board,axis=1)==-3)):
            return -1
        # diagonals 
        if (np.trace(self.board))==3 or (np.trace(np.fliplr(self.board)))==3:
            return 1
        if (np.trace(self.board))==-3 or (np.trace(np.fliplr(self.board)))==-3:
            return -1
        if(self._alldone()):
            return 0
        return None
    def _alldone(self):
        return not np.any(self.board==0)
        
    def availble_positions(self):
        ans = []
        for i in range(3):
            for j in range(3):
                if(self.board[i][j]==0):
                    ans.append((i,j))
        return ans
    def print_board(self):
        for i in self.board:
            print(i)
            

In [12]:
class Game(Board):
    def __init__(self,p1=1,p2=-1):
        super().__init__()
        self.p1 = p1
        self.p2 =p2
    
    def play(self):
        """
        the main runner of the game its where we give the input and the 
        adversial search gives back its input
        we check if the game is won/tied 
        if not repeat the process
        """
        
        while True:
            self.print_board()
            print("you can take any position which is 0")
            i = int(input("enter your row: "))
            j = int(input("enter your col: "))
            
            if(self.board[i][j]==0):
                self.board[i][j]= 1
            else :
                print("invalid move")
                continue

            self.board[i][j]=1;
            if(self.winning()) is not None :
                break

            ai_move = self.best_move()
            self.board[ai_move[0]][ai_move[1]]=-1
            if self.winning() is not None :
                break
    
    def best_move(self):
        best_score = -1e-15
        move = None

        for (i,j) in self.availble_positions():
            self.board[i][j]--1
            score = self.minimax(False)
            self.board[i][j]=0

            if score>best_score:
                best_score = score
                move = (i,j)

        return move
    
    def minimax(self,maximising):
        result = self.winning()
        if result is not None:
            return result
        if maximising:
            best = -1e-15
            for (i,j) in self.availble_positions():
                self.board[i][j]=-1
                score = self.minimax(False)
                self.board[i][j]=0
                best = max(score,best)
            return best
        else:
            best = 1e15
            for(i,j)in self.availble_positions():
                self.board[i][j]=1
                score = self.minimax(True)
                self.board[i][j]=0
                best = min(score,best)
            return best



In [13]:
game = Game()
print(game.availble_positions())
game.play()

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
you can take any position which is 0
[ 1. -1.  0.]
[0. 0. 0.]
[0. 0. 0.]
you can take any position which is 0


ValueError: invalid literal for int() with base 10: ''

In [ ]:
# to implement the alpha beta pruning redefining our game class 
class Game(Board):
    def __init__(self,p1=1,p2=-1):
        super().__init__()
        self.p1 = p1
        self.p2 =p2
    
    def play(self):
        """
        the main runner of the game its where we give the input and the 
        adversial search gives back its input
        we check if the game is won/tied 
        if not repeat the process
        """
        
        while True:
            self.print_board()
            print("you can take any position which is 0")
            i = int(input("enter your row: "))
            j = int(input("enter your col: "))
            
            if(self.board[i][j]==0):
                self.board[i][j]= 1
            else :
                print("invalid move")
                continue

            self.board[i][j]=1;
            if(self.winning()) is not None :
                break

            ai_move = self.best_move()
            self.board[ai_move[0]][ai_move[1]]=-1
            if self.winning() is not None :
                break
    
    def best_move(self):
        best_score = -1e-15
        move = None

        for (i,j) in self.availble_positions():
            self.board[i][j]--1
            score = self.minimax(False,-1e-15,1e15)
            self.board[i][j]=0

            if score>best_score:
                best_score = score
                move = (i,j)

        return move
    
    def minimax(self,maximising,alpha,beta):
        result = self.winning()
        if result is not None:
            return result
        if maximising:
            best = -1e-15
            for (i,j) in self.availble_positions():
                self.board[i][j]=-1
                score = self.minimax(False,alpha,beta)
                self.board[i][j]=0
                best = max(score,best)
                alpha = max(alpha, best)
                if alpha>=beta:
                    break
            return best
        else:
            best = 1e15
            for(i,j)in self.availble_positions():
                self.board[i][j]=1
                score = self.minimax(True,alpha,beta)
                self.board[i][j]=0
                best = min(score,best)
                beta = min(beta, best)
                if alpha>=beta:
                    break

            return best

