In [1]:
import numpy as np
import pickle 
import pandas as pd
import heapq
import copy

In [2]:
# we first need to make a node class to amke sure we confer to the 
# rules of the game 
class Node:
    def __init__(self,board,level,fval):
        self.board = board
        self.level = level
        self.fval= fval 
    def find(self,board,x):
        """find the x in the board to find blank space"""
        for i in range(len(self.data)):
            for j in range(len(self.data)):
                if board[i][j]== x:
                    return i,j
    def valid(self, x,y):
        if(x>=0 and x<= len(self.data) and y>=0 and y<= len(self.data) ):
            return True
        else:
            return False
    def its_children(self):
        x,y = self.find(self.board,0)
        moves = [
            [x,y-1],
            [x,y+1],
            [x-1,y],
            [x+1,y]
        ]
        valid_moves=[]
        for i in moves:
            if(self.valid(i[0],i[1])):
                valid_moves.append(i)
        children = []
        for i in valid_moves :
            child = self.move(self.board, x,y,i[0],i[1])
            child_node = Node(child,self.level+1,0)
            children.append(child_node)
        return children
    def move(self, board, i1,j1,i2,j2):
        """i1, j1 is the blank space 
        i2, j2 is the place to be moved"""
        child = copy.deepcopy(board)
        child[i1][j1]= child[i2][j2]
        child[i2][j1]= 0
        return child
        
    
        

In [11]:
# let h be the no of the wrong placemtns
# let g be the no fo levels to get to here 
class Solve:
    def __init__(self,size,game,final_state):
        self.n = size
        self.open = []
        self.closed = []
        self.game = game
        self.final_state= final_state
        
    def h (self,board,goal):
        ct =0 
        for i in range(self.n):
            for j in range(self.n):
                if board[i][j]!= goal[i][j] and board:
                    ct+=1
        return ct
    def g(self, board):
        return board.level
    
    def f (self, board):
        return self.h(board,self.final_state)+ self.g(board)
    
    def running(self):
        start = self.game
        goal = self.final_state

        start = Node(start,0,0)
        start.fval = self.f(start)

        self.open.append(start)
        while True:
            current = self.open[0]
            for i in current.data:
                for j in i:
                    print(j,end=" ")
                print("")
            if(self.h(current.data,goal)==0):
                break

            for i in current.its_children():
                i.fval = self.f(i,goal)
                self.open.append(i)
            
            self.closed.append(current)
            del self.open[0]

            self.open.sort(key=lambda x: x.fval,reverse=False)

    

    

In [5]:

game = np.arange(1,9)
game = np.append(game,0)
final_state = game.reshape((3,3))
np.random.shuffle(game)
game = game.reshape((3,3))
print(game)


[[1 3 8]
 [4 0 7]
 [2 5 6]]


In [12]:
puz = Solve(3,game,final_state)
puz.running()

TypeError: 'Node' object is not subscriptable